name: 'dw'
version: '1.0'

profile: 'Snowflake'

source-paths: ["models"]
macro-paths: ["macros"]

models:
  dw:
    enabled: true
    materialized: table
    staging:
      materialized: table
      schema: staging 

quoting:
  database: false
  identifier: false
  schema: false