version: 2

sources:
  - name: datalake
    database: dbt
    schema: datalake
    description: "extracted Cassini data"

    quoting:
      database: false
      schema: false
      identifier: false
      
    tables:
      - name: chem_data
      - name: inms
      - name: jpl_flybys
